name: shopiera
description: "A modern Flutter e-commerce app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider:
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.7

  # Networking
  dio: ^5.3.3
  http:
  flutter_dotenv: ^5.1.0
  firebase_core:
  firebase_auth:


  # Local Storage
  shared_preferences: ^2.2.2

  # UI
  flutter_credit_card: ^3.0.1
  lottie: ^3.3.1
  flutter_svg: ^2.0.10
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.1

  # Utilities
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

    - assets/images/shopiera2.jpg
    - assets/images/shopiera_gorsel.jpg
    - assets/images/shopiera_gorsel2.png
    - assets/images/shopiera_güncel.png
    - assets/images/Shopieramankenligörsel.jpg
